import Head from 'next/head'
import Navigation from '../components/Navigation'
import Footer from '../components/Footer'
import {useRouter} from 'next/router'
import { useState } from 'react'

import { useEffect } from 'react'
import { useDispatch , useSelector } from 'react-redux'

//STATE
import { getCurrentWidth } from '../store/slices/InterfaceSlice'

const NavigationFooter = ({children}) => {
    const [title, setTitle] = useState('Home | Skyflix')
    const titlePath = [
        {pathname: "/movie/[mode]", name: "Movie Shows | Skyflix"},
        {pathname: "/tv/[mode]", name: "TV Shows | Skyflix"},
        {pathname: "/", name: "Skyflix"},
        {pathname: "/person", name: "Popular Persons | Skyflix"},
        {pathname: "/discover/[show]", name: "Discover Shows | Skyflix"},
    ]
    const router = useRouter()
    const dispatch = useDispatch()
    const currentWidth = useSelector(state => state.browserInterface.currentWidth)

    useEffect(() => {
        if (router.query.page) {
            setTitle(titlePath.find(path => path.pathname === router.pathname).name)
            console.log('hhahah')
        }
    }, [router])

    useEffect(() => {
        dispatch(getCurrentWidth())
        window.addEventListener('resize', () => dispatch(getCurrentWidth()))
    }, [currentWidth])


    return (
        <>
            <Head>
                <title className="capitalize">{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
                <div className="h-[4.5rem] w-full opacity-0 sm:h-[6rem]"></div>
                {children}
            <Footer />
        </>
    )
}

export default NavigationFooter